default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode

development:
  <<: *default
  database: myapp_development
  username: david

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: df5gi36re1tme5
  username: jvwnkpillpxudm
  password: UmWKU_qRPgLi-OX3-lJ5XzrJYU
  port: 5432
  host: ec2-54-221-253-117.compute-1.amazonaws.com